# Scavenger Hunt Code with Comment Version

## Teammembers:


### Before the start:

- Did you finish all five tutorials posted under `Python Workshops` on myCourses? If not, please first do it.

- Read the instruction `Assignment 3 - Data Scavenger Hunt` and follow what the goal is. Use Slack to exchange understanding.


***

# Code Portion

In [1]:
# In Terminal, run > pwd and obtain the directory address
# Then run: cd 'directory address here'
# Then run the cells one by one
# Add your own comments if you like

import matplotlib.pyplot as plt
import numpy as np

In [2]:
def read_waveforms(LA, RV, RA) :
    infile = open('waveforms.csv', 'r')

    line = infile.readline()
    wf = 0 # which waveform are we trying to read (0 = LA, 1 = RV, 2 = RA)

    while line :
        line = line.strip()
        data = line.split(',')

        for i in range(0, len(data)) : 
            data[i] = float(data[i])

        if(wf == 0) :
            LA.append(data)
        elif(wf == 1) :
            RV.append(data)
        elif(wf == 2) :
            RA.append(data)
        
        wf = (wf + 1) % 3
        line = infile.readline()

    infile.close()

In [3]:
def read_times(TL, TR) :
    infile = open('times.csv', 'r')
    line = infile.readline()
    data = line.strip().split(',')

    for i in range(0, len(data)) : 
        data[i] = float(data[i])

    TL.append(data)

    line = infile.readline()
    data = line.strip().split(',')

    for i in range(0, len(data)) : 
        data[i] = float(data[i])

    TR.append(data)
    infile.close()

def plot_waveforms(LA, RV, RA, TL, TR) :
    print('create your individual waveform plots here')

In [4]:
# make empty data and time Lists
LA_list = []
RV_list = []
RA_list = []
TL_list = []
TR_list = []

# Run the fns
read_waveforms(LA_list, RV_list, RA_list)

read_times(TL_list, TR_list)

# convert all data and time lists to numpy arrays for plotting
LA = np.array(LA_list)
RV = np.array(RV_list)
RA = np.array(RA_list)
TL = np.array(TL_list[0])
TR = np.array(TR_list[0])

In [7]:
print(TR)

[0.     0.0005 0.001  0.0015 0.002  0.0025 0.003  0.0035 0.004  0.0045
 0.005  0.0055 0.006  0.0065 0.007  0.0075 0.008  0.0085 0.009  0.0095
 0.01   0.0105 0.011  0.0115 0.012  0.0125 0.013  0.0135 0.014  0.0145
 0.015  0.0155 0.016  0.0165 0.017  0.0175 0.018  0.0185 0.019  0.0195
 0.02   0.0205 0.021  0.0215 0.022  0.0225 0.023  0.0235 0.024  0.0245
 0.025  0.0255 0.026  0.0265 0.027  0.0275 0.028  0.0285 0.029  0.0295
 0.03   0.0305 0.031  0.0315 0.032  0.0325 0.033  0.0335 0.034  0.0345
 0.035  0.0355 0.036  0.0365 0.037  0.0375 0.038  0.0385 0.039  0.0395
 0.04   0.0405 0.041  0.0415 0.042  0.0425 0.043  0.0435 0.044  0.0445
 0.045  0.0455 0.046  0.0465 0.047  0.0475 0.048  0.0485 0.049  0.0495
 0.05  ]


In [8]:
# make empty data and time Lists
LA_list = []
RV_list = []
RA_list = []
TL_list = []
TR_list = []

# Again
read_waveforms(LA_list, RV_list, RA_list)

read_times(TL_list, TR_list)

# convert all data and time lists to numpy arrays for plotting
LA = np.array(LA_list)
RV = np.array(RV_list)
RA = np.array(RA_list)
TL = np.array(TL_list[0])
TR = np.array(TR_list[0])

In [11]:
print(LA)

[[1.4729e+00 1.9103e+00 1.7495e+00 ... 6.9122e-01 4.4614e-01 5.4853e-01]
 [5.4563e-01 5.4037e-01 5.9305e-01 ... 1.3645e-01 3.2749e-01 4.9801e-01]
 [4.2653e+00 4.3696e+00 5.5504e+00 ... 1.1709e-02 1.5196e-01 3.7465e-01]
 ...
 [5.3061e+00 4.2653e+00 5.1861e+00 ... 4.5459e-01 8.6968e-01 9.7583e-01]
 [6.0754e+00 6.8808e+00 7.6102e+00 ... 1.4169e+00 2.0462e+00 1.7491e+00]
 [3.6420e+00 4.3162e+00 6.5301e+00 ... 0.0000e+00 6.5368e-04 3.0995e-02]]


In [16]:
print(LA.dtype)

print(LA)

float64
[[1.4729e+00 1.9103e+00 1.7495e+00 ... 6.9122e-01 4.4614e-01 5.4853e-01]
 [5.4563e-01 5.4037e-01 5.9305e-01 ... 1.3645e-01 3.2749e-01 4.9801e-01]
 [4.2653e+00 4.3696e+00 5.5504e+00 ... 1.1709e-02 1.5196e-01 3.7465e-01]
 ...
 [5.3061e+00 4.2653e+00 5.1861e+00 ... 4.5459e-01 8.6968e-01 9.7583e-01]
 [6.0754e+00 6.8808e+00 7.6102e+00 ... 1.4169e+00 2.0462e+00 1.7491e+00]
 [3.6420e+00 4.3162e+00 6.5301e+00 ... 0.0000e+00 6.5368e-04 3.0995e-02]]


## Did you see a bug in the data waveforms.csv?

- Open the data waveforms.csv, see the column names are not defined and first row became the names

- Now, fix it first.

- Then complete the assignment under Write-up as described in the instruction.


## Your turn to play with code

- Fix, play, obtain plots etc
- Finding effective visualization portion will take your time
- Then you will write up to address the goal / questions in the assignment

***

# Your Write-up

- Use Markdown and elegant formats as a professional report. You can include the plots, but do not include code in thie write-up (it is like a report on what you found and how you addressed the task).